### ISSUE TITLE
6.0的系统有问题

### ISSUE THREAD

**Issue by hybirdtheory** [zfdang/android-multiple-images-selector#1]
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=10398, uid=10107 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

加了权限也显示不出来

**Comment by zfdang** [comment]
this library does not handle the runtime permission in android 6.0.  please upgrade to v1.1.3. this issue should have been fixed.
