### ISSUE TITLE
师兄好，请问下微信里保存到手机的一张图片，通过这个组件为什么找不到？急需你的帮助

### ISSUE THREAD

**Issue by fangcaiwen** [zfdang/android-multiple-images-selector#13]
这是我的qq，1554196146，加我时说明下你是谁，多谢啦

**Comment by lianghuacheng** [comment]
@fangcaiwen 在设置里面可以设置图片的最小的大小

**Comment by fangcaiwen** [comment]
@lianghuacheng 请问下这个单位是啥？

**Comment by lianghuacheng** [comment]
@fangcaiwen 我觉得是B 吧

**Comment by SuperTxy** [comment]
楼上的问题解决了吗？微信保存的图片显示不了，我看着路径是对的

**Comment by zfdang** [comment]
这个selector可以设置显示图片的最小文件大小，如果文件过小就不会显示。如果微信保存的文件太小，你设置的最小文件大小又偏大，那图片就显示不出来。

**Comment by zfdang** [comment]
// min size of image which will be shown; to filter tiny images (mainly icons)
intent.putExtra(SelectorSettings.SELECTOR_MIN_IMAGE_SIZE, 100000);
