### ISSUE TITLE
手机开启硬件加速后，图库直接崩溃

### ISSUE THREAD

**Issue by Stevenxin** [zfdang/android-multiple-images-selector#4]
android:hardwareAccelerated="true" application中开启硬件加速后，图库中图片量比较大直接崩了，华为Mate8手机。
关闭硬件加速false，就好了，但是我的项目必须得打开硬件加速，显示比如CardView的阴影效果

求解？

**Comment by zfdang** [comment]
android:hardwareAccelerated="true" 可以针对activity单独设置，不行的话你把image selector activity的加速单独关闭试试吧

**Comment by Stevenxin** [comment]
在“com.zfdang.multiple_images_selector.ImagesSelectorActivity"中设置了 android:hardwareAccelerated="false" ，图片量较大没有崩溃了
