### ISSUE TITLE
第一次进去选择了图片之后，第二次进去图片选择界面，怎样取消掉上次已经选择的图片？

### ISSUE THREAD

**Issue by MaleWxt** [zfdang/android-multiple-images-selector#6]
我现在就用的这个，做一些图片上传，但是第一次选了几张照片之后，第二次进去第一次选的照片被默认选中了，我暂时还没解决这个问题，请问一下有人能帮忙解决一下吗？

**Comment by zfdang** [comment]
清空ArrayList<String> mResults就可以了
